import { test, expect } from '@playwright/test';
import { setupTMDBMocks } from './helpers/mock-tmdb';
import { seedSeries, clearLibrary } from './helpers/seed';

const TMDB_ID = 1396; // Breaking Bad
const IMDB_ID = 'tt0903747';
const STUBBED_RECAP =
  "In this gripping episode, the tension reaches a breaking point as Walt makes a decision that will have far-reaching consequences. Jesse is forced to confront the reality of their situation while the walls close in around them. Meanwhile, Skyler grows increasingly suspicious of Walt's behavior, setting the stage for a dramatic confrontation.";

/** Navigate to the Episodes tab for the seeded series. */
async function goToEpisodesTab(page: Parameters<typeof setupTMDBMocks>[0]) {
  await setupTMDBMocks(page);
  await page.goto(`/series/${TMDB_ID}`);
  await page.getByRole('button', { name: 'Episodes' }).click();
}

/** Toggle a single episode watched via the REST API. */
async function watchEpisode(
  request: { post: (url: string, opts: { data: unknown }) => Promise<unknown> },
  episode: number,
  season = 1,
) {
  await (request as import('@playwright/test').APIRequestContext).post('/api/episodes/toggle', {
    data: { tmdbId: TMDB_ID, season, episode },
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Recap button visibility
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Episode Recap — button visibility', () => {
  test.beforeEach(async ({ request }) => {
    await clearLibrary(request);
    await seedSeries(request, { status: 'watching' });
  });

  test('recap button is not shown when no episodes are watched', async ({ page }) => {
    await goToEpisodesTab(page);
    await expect(page.getByRole('button', { name: 'Recap' })).not.toBeVisible();
  });

  test('recap button appears on the only watched episode', async ({ page, request }) => {
    await watchEpisode(request, 1);
    await goToEpisodesTab(page);
    await expect(page.getByRole('button', { name: 'Recap' })).toBeVisible();
  });

  test('recap button is on episode 1 when only ep 1 is watched', async ({ page, request }) => {
    await watchEpisode(request, 1);
    await goToEpisodesTab(page);
    // The recap button must be inside the row for episode 1
    const ep1Row = page.locator('[data-episode="1"]');
    await expect(ep1Row.getByRole('button', { name: 'Recap' })).toBeVisible();
  });

  test('recap button moves to ep 2 when eps 1 and 2 are watched', async ({ page, request }) => {
    await watchEpisode(request, 1);
    await watchEpisode(request, 2);
    await goToEpisodesTab(page);
    const ep2Row = page.locator('[data-episode="2"]');
    await expect(ep2Row.getByRole('button', { name: 'Recap' })).toBeVisible();
  });

  test('recap button is NOT shown on ep 1 when ep 2 is also watched', async ({
    page,
    request,
  }) => {
    await watchEpisode(request, 1);
    await watchEpisode(request, 2);
    await goToEpisodesTab(page);
    const ep1Row = page.locator('[data-episode="1"]');
    await expect(ep1Row.getByRole('button', { name: 'Recap' })).not.toBeVisible();
  });

  test('recap button is only shown once in the list', async ({ page, request }) => {
    await watchEpisode(request, 1);
    await watchEpisode(request, 2);
    await watchEpisode(request, 3);
    await goToEpisodesTab(page);
    await expect(page.getByRole('button', { name: 'Recap' })).toHaveCount(1);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Modal — opening and content
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Episode Recap — modal', () => {
  test.beforeEach(async ({ request }) => {
    await clearLibrary(request);
    await seedSeries(request, { status: 'watching' });
    await watchEpisode(request, 1);
  });

  test('clicking Recap opens the modal', async ({ page }) => {
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    // The modal shows "Generated by GitHub Copilot" footer — unique to the modal
    await expect(page.getByText('Generated by GitHub Copilot')).toBeVisible();
  });

  test('modal header shows correct series name and episode code', async ({ page }) => {
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    await expect(page.getByText(/Breaking Bad.*S01E01/)).toBeVisible();
  });

  test('modal header shows correct episode title', async ({ page }) => {
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    await expect(page.getByRole('heading', { name: 'Pilot' })).toBeVisible();
  });

  test('modal shows loading spinner while generating', async ({ page }) => {
    // Delay the recap response so the loading state is visible
    await page.route('**/api/recap/episode', async (route) => {
      await new Promise<void>((resolve) => setTimeout(resolve, 600));
      await route.fulfill({ json: { recap: STUBBED_RECAP } });
    });
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    await expect(page.getByText('Generating recap...')).toBeVisible();
  });

  test('modal shows the recap text returned by the API', async ({ page }) => {
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    await expect(page.getByText(STUBBED_RECAP)).toBeVisible();
  });

  test('modal shows "Generated by GitHub Copilot" footer', async ({ page }) => {
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    await expect(page.getByText('Generated by GitHub Copilot')).toBeVisible();
  });

  test('modal shows error message when API returns an error', async ({ page }) => {
    await page.route('**/api/recap/episode', (route) =>
      route.fulfill({ status: 500, json: { error: 'Series not found on TVMaze' } }),
    );
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    await expect(page.getByText('Series not found on TVMaze')).toBeVisible();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Modal — closing
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Episode Recap — closing the modal', () => {
  test.beforeEach(async ({ request }) => {
    await clearLibrary(request);
    await seedSeries(request, { status: 'watching' });
    await watchEpisode(request, 1);
  });

  test('modal closes when the X button is clicked', async ({ page }) => {
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    await expect(page.getByText('Generated by GitHub Copilot')).toBeVisible();
    await page.getByRole('button', { name: 'Close' }).click();
    await expect(page.getByText('Generated by GitHub Copilot')).not.toBeVisible();
  });

  test('modal closes when clicking the backdrop', async ({ page }) => {
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    await expect(page.getByText('Generated by GitHub Copilot')).toBeVisible();
    // Click the fixed overlay container (outside the modal panel)
    await page.locator('.fixed.inset-0.z-50').first().click({ position: { x: 10, y: 10 } });
    await expect(page.getByText('Generated by GitHub Copilot')).not.toBeVisible();
  });

  test('modal closes when pressing Escape', async ({ page }) => {
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    await expect(page.getByText('Generated by GitHub Copilot')).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.getByText('Generated by GitHub Copilot')).not.toBeVisible();
  });

  test('recap button is still visible after closing the modal', async ({ page }) => {
    await goToEpisodesTab(page);
    await page.getByRole('button', { name: 'Recap' }).click();
    await page.keyboard.press('Escape');
    await expect(page.getByRole('button', { name: 'Recap' })).toBeVisible();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Settings — Episode Recap toggle
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Episode Recap — Settings toggle', () => {
  test.beforeEach(async ({ request }) => {
    await clearLibrary(request);
    await seedSeries(request, { status: 'watching' });
    await watchEpisode(request, 1);
    // Reset episode recap setting to its default (enabled) before each test
    await request.put('/api/settings', {
      data: { episodeRecapEnabled: true },
    });
  });

  test('Episode Recap toggle is visible in the Preferences section', async ({ page }) => {
    await setupTMDBMocks(page);
    await page.goto('/settings');
    await expect(
      page.locator('.flex.items-center.justify-between').filter({ hasText: 'Episode Recap' }),
    ).toBeVisible();
  });

  test('Episode Recap toggle is on by default', async ({ page }) => {
    await setupTMDBMocks(page);
    await page.goto('/settings', { waitUntil: 'networkidle' });
    const toggle = page
      .locator('.flex.items-center.justify-between')
      .filter({ hasText: 'Episode Recap' })
      .getByRole('switch');
    await expect(toggle).toHaveAttribute('aria-checked', 'true');
  });

  test('disabling Episode Recap hides the recap button on the series page', async ({
    page,
    request,
  }) => {
    // Disable via API so the setting is persisted before page load
    await request.put('/api/settings', { data: { episodeRecapEnabled: false } });
    await goToEpisodesTab(page);
    await expect(page.getByRole('button', { name: 'Recap' })).not.toBeVisible();
  });

  test('re-enabling Episode Recap shows the recap button again', async ({ page, request }) => {
    await request.put('/api/settings', { data: { episodeRecapEnabled: false } });
    await goToEpisodesTab(page);
    await expect(page.getByRole('button', { name: 'Recap' })).not.toBeVisible();

    // Re-enable via settings page
    await page.goto('/settings', { waitUntil: 'networkidle' });
    const toggle = page
      .locator('.flex.items-center.justify-between')
      .filter({ hasText: 'Episode Recap' })
      .getByRole('switch');
    await toggle.click();
    await expect(toggle).toHaveAttribute('aria-checked', 'true');

    // Navigate back and confirm the button is back
    await goToEpisodesTab(page);
    await expect(page.getByRole('button', { name: 'Recap' })).toBeVisible();
  });

  test('toggling Episode Recap off in settings persists after re-navigation', async ({
    page,
    request,
  }) => {
    await request.put('/api/settings', { data: { episodeRecapEnabled: false } });
    // First visit — no button
    await goToEpisodesTab(page);
    await expect(page.getByRole('button', { name: 'Recap' })).not.toBeVisible();
    // Navigate away and back
    await page.goto('/library');
    await goToEpisodesTab(page);
    await expect(page.getByRole('button', { name: 'Recap' })).not.toBeVisible();
  });
});
